monome/ansible

src/ansible_midi.c
src/ansible_midi.h
src/config.mk

this is the **second** of three PRs:
* https://github.com/monome/libavr32/pull/24
* this
* teletype
_**the libavr32 changes must be merged before this one**_
general changes:
- full teletype support (documentation forthcoming)
- better config save gesture (two keys instead of one)
- midi clock output changed from 1/8th to 1/16th notes
- (nearly) all parameters saved/restored between mode switch and preset config in flash
- default note to cv mapping is -2 octaves
arp mode:
- [new] key 2 + key 1 toggles on hold
- [new] pattern style (as played)
- [new] pattern steps (0 to 8)
- [new] pattern offset (-24 to +24 semitones)
- no longer restart arp pattern when the keys change (makes arp useable imho)
- pitch slewing
- tuning offset
standard mode:
- pitch slewing 
- tuning offset

ansible midi mode v2

---

src/ansible_midi.c
src/config.mk

Please merge https://github.com/monome/libavr32/pull/26 first

update for msc and timer changes in libavr32

---

src/ansible_midi.c
src/config.mk

updated for libavr32 changes to IRQ pause/resume functions. (this is currently causing travis to fail for libavr32.)
i don't have ansible hardware so can't really test it!
@ngwese seems like midi would be directly affected if i did this wrong...

update IRQ functions to sync with libavr32 changes

---

src/ansible_grid.c

I [noticed](https://llllllll.co/t/ansible-meadowphysics-note-mode/4809/13?u=saeflod) that meadowphysics doesn't trigger when the voice mode is set to 1 CV/TR.
In `mp_note_on()`, it looks like this is due to `if(mp_clock_count)` never passing due to `mp_clock_count` being initialized to 0 in `clock_mp()`. Since it never passes, `mp_clock_count` is never incremented and a voice is never allocated.
The solution is to properly check the value of `mp_clock_count`, just like the other voice allocation modes. (It could just as easily be `mp_clock_count == 0`, but I thought this was clearer.)
(I've also included some whitespace changes here that I'd be happy to remove if you don't want them.)

(meadowphysics) fix tigger behaviour in 1 CV/TR

---

src/ansible_grid.c

at max duration tied notes still had gaps, this should fix it. checked with oscilloscope, no gaps as far as i can tell. using value of 381 or higher still produces gaps.

fix for tied notes

---

src/ansible_grid.c
src/ansible_grid.h

As proposed in [this](https://llllllll.co/t/ansible-kria-feature-requests/4846/93) post:
* Add a per-track direction select for forward/reverse/triangle/drunk modes on the scale page
* Changes the Teletype clock enables to be the first column of keys on the scale page rather than the first row

kria: forward/reverse/triangle/drunk direction select

---

src/ansible_grid.c
src/ansible_grid.h

I immediately found a bug in reverse mode in the [previous MR](https://github.com/monome/ansible/pull/40) when loop start/end points are swapped. This fixes that issue and also adds random mode.

fix reverse bug for swapped loops, add random

---

src/ansible_grid.c
src/ansible_grid.h

This was causing all parameters to change direction when any parameter reached the end of its loop, reported [here](https://llllllll.co/t/ansible-kria-feature-requests/4846/146?u=csboling). Pushed the state for this down to the parameter level.

 triangle forward/reverse state should be per-parameter 

---

src/ansible_grid.c
src/ansible_grid.h

Moves Teletype clock enable settings to `kria_track` so they're saved to flash, [discussion](https://llllllll.co/t/ansible-kria-feature-requests/4846/148).

kria: move tt clock enables to track state

---

.gitignore
src/ansible_grid.c
src/ansible_grid.h

Fixes #25 
On Kria's config page, adds a toggle below the note sync square for enabling this feature. When enabled, changing a time division for a parameter will take effect only when that parameter's loop reaches its end. Given that step direction is now configurable, this takes effect at the opposite end of the loop when in reverse mode, and at both ends of the loop when in triangle mode. In drunk and random step modes this setting is ignored.

kria: optionally phase sync on time div change

---

src/ansible_grid.c
src/ansible_grid.h

Fixes #29 
Video [here](https://llllllll.co/t/ansible-kria-feature-requests/4846/173). This adds an octave shift per track on the octave page along the top row. When the octave shift is engaged for a track, the "home row" of the octave page moves up a corresponding number of keys. This allows you to transpose some notes down one or more octaves from the root.
When transposing up a couple octaves, it seemed kind of cramped to have a ceiling on the amount of octave transposition, so in this change all notes have a full 0-5V octave range at all times. One downside of this is that it pretty much uses up the whole octave page. It would be straightforward to impose a lower ceiling than 5V for the maximum octave to get some more UI space back and constrain the pitch CV range.

kria: track-wide octave shift and negative octave transposition

---

src/ansible_grid.c
src/ansible_grid.h
src/ansible_preset_docdef.c

Binaries + videos [here](https://llllllll.co/t/ansible-development-and-beta-firmware-discussion/23118).
* Ability to toggle individual gates off and on within each note on the ratchet page
* Ability to select number of subdivisions on the ratchet page, so you can e.g. have rests at the end of a note step, using row 0 (top row) and row 6 on the ratchet page. Number of subdivisions is automatically set when you enable a gate. Long pressing row 6 will clear the ratchet settings, so only a single note is played without being subdivided. Long pressing row 0 will set the subdivision count equal to the latest gate you have selected, so that there are no rests at the end of the step.
* [Trigger clocking](https://llllllll.co/t/kria-feature-trigger-step-params/14501), concept and original code by …

kria: some advanced note placement features

---

src/ansible_arc.c
src/ansible_arc.h
src/ansible_grid.c
src/ansible_grid.h
src/ansible_midi.c
src/ansible_tt.c
src/main.c
src/main.h

* Restructures the "null" i2c handler a little bit so that it can support messages that affect the whole module. Other `ii_` functions call this `ii_ansible` handler as a fallback if they don't understand a message.
* Adds Ansible support for the following TT remote ops: `ANS.G`, `ANS.G.P`, `ANS.G.LED`, `ANS.A`, `ANS.A.LED`, `ANS.APP`, `KR.CUE`, `KR.PG`. These allow i2c messages to simulate a grid or arc event, i.e. post an event to the event queue as though a grid key were pressed or an arc ring were rotated, as well as getting/setting the active app remotely.
* Fixes #35 via `KR.CUE` implementation.

Support for new TT remote ops

---

src/ansible_grid.c
src/ansible_grid.h
src/ansible_preset_docdef.c

* In analogy with note sync/loop sync, adds the ability to simultaneously apply time division changes across all tracks, all parameters within a track, or only trigger + note within each track while leaving other parameters independent. These settings are configured by glyphs on the clock config page that look like the ones on the config page.
* Moves the "phase sync on time div changes" to a glyph on the bottom center of the clock config page, since it seemed to fit in better here. Going to call this feature "division cueing" rather than "division sync", as I think "division sync" makes more sense for the first item above.
* Adds `sync_mode` (for configuring whether to cue divisions) to the docdef so it will be saved to disk, this was missing.
Discussion …

kria: share div changes across all, track, or trig+note

---

src/ansible_grid.c

Performance feature proposed [here](https://llllllll.co/t/ansible-development-and-beta-firmware-discussion/23118/52) which allows you to use a two-key gesture on the scale page to offset certain scale steps without affecting the rest of the scale. These are cleared when you change the selected scale, but not on a pattern change, and they are not persisted to flash.

feature(kria/mp): apply temporary shift to scale steps

---

src/ansible_preset_docdef.c

I had incorrect item counts in a couple of docdef items after some recent changes, this was causing Kria not to save or load presets to disk. Really should figure out some way to make that mistake harder to make... Also track-wide octave shifts were not being saved.

bugfix(kria): broken docdef after note placement changes

---

src/ansible_grid.c

After the changes for note sync on + loop sync off, relocating the loop by holding the Loop Mod key and pressing a loop start point was not working on the Trigger and Note pages, it would always set a 1-step loop.

bugfix(kria): fix relocating loop on trig + note pages

---

src/ansible_grid.c

The loop for highlighting the selected loop on the note page was using the iteration index instead of the calculated x position to determine which keys should be highlighted, so spurious notes were being drawn when the loop wrapped around the end. Reported [here](https://llllllll.co/t/ansible-development-and-beta-firmware-discussion/23118/84).

bugfix(kria): note page display bug when loop endpoints are swapped

---

src/ansible_grid.c

Ability to select which brightness settings to accommodate grids with different numbers of variable brightness steps. Previously this was only available through the JSON file, now it can be set via the top-left 3 keys of the Kria config page. This space is unused on Meadowphysics but is immediately adjacent to the 8 trigger voice select and seemed confusing, and Earthsea doesn't have a config page.

feature: grid varibrightness select on top row of kria config page

---

src/ansible_grid.c

The opposite loop start adjustment was working fine, as was updating both ends of either loop.

bugfix(kria): moving tr loop start didn't update note loop w/ note sync

---

src/ansible_preset_docdef.c
src/ansible_usb_disk.c
tools/flash_tools/preset_schema.py
tools/flash_tools/schemata/ansible/v161.py

* Negative int16 fields in hex dump would cause conversion to fail
* Missing size meant presence of ES preset glyphs in JSON would cause load to fail
* Now that ratchet behavior depends on `rpt` and `rptBits` state, both need to be populated when producing a JSON file
* Clear clock handler of running app when entering USB disk mode, because it could interfere with the busy indicator

bugfix: some issues with 1.6.1 + ES -> 2.0.0 upgrade path

---

src/ansible_arc.c
src/ansible_grid.c
src/ansible_grid.h
src/ansible_preset_docdef.c
src/config.mk
src/main.c
src/main.h

Instead of using the `ET[]` pitch lookup table directly, pitch assignments are made using a per-track `tuning_table[4][120]` which is stored / loaded in top-level flash state. This is loaded by default with `ET[i] << 2`, rather than using `<< 2` when calling `dac_set_value`, so that the 2 least significant bits of each tuning table slot are available for user adjustment.
To aid in calibration or experimental retuning, a Grid interface is added which allows reassigning tuning tables and saving/loading them to flash. All tracks may have all tuning table slots assigned independently across the full 10V range. To help with the most common retuning workflows, piecewise-linear interpolation between assigned octave values is available. This interpolation is implemented using `fix16.c` from …

feature: tuning table reassignment interface

---

src/ansible_usb_disk.c
src/ansible_usb_disk.h
src/main.c

Had someone report the first disk they tried wasn't working, but others were, so I wanted to check through it again. The things I think I actually fixed that are meaningful are:
* LED didn't turn off when you remove the drive if there was an error during disk access, which I thought it did when I claimed that it did in the docs
* If the file doesn't exist, don't create a 0 byte file by opening the file read + create
I dredged up a handful of disks from the deeper strata of my desk drawer, most worked, some didn't either before or after this patch. So I'm not sure I improved things on that front. Will note in the docs that it can be picky about your choice of disk I guess, hopefully this works in most cases.

bugfix?: check more USB disk stuff

---

src/ansible_arc.c
src/ansible_preset_docdef.c
src/main.h

Two tiny goofs that made Levels and MIDI apps unusable:
* I apparently got confused about flow control in `levels_dac_refresh` when working on tuning
* Some key enums are saved to JSON as strings specifically to improve backwards compatibility, but this does mean when a mode (Earthsea) is added that the string representation has to be added to the docdef as well. This was missing which caused MIDI to fail to load the right app when a device was plugged in. Added warning comments around this in both files.

bugfix: fix levels & midi after preset load

---

src/ansible_grid.c
src/flash.sh
src/update-firmware.command

Useful for adding an offset to all DAC channels so you have some footroom while tuning the lowest note slot.
Also includes bug fixes for:
* keys on the 4th row of tuning mode cause would buffer overrun
* clock keys on the left side of clock config mode would toggle note div sync glyph
* changed reflashing scripts (update-firmware.command, flash.sh) from 0256 to 0512 chip. This should not really matter in practice, flashing with 0256 works fine, but reading with 0256 doesn't and I figured this should be made consistent.

feature(tuning): mod key to retune all slots at once

---

src/ansible_preset_docdef.c

I could have sworn I fixed this already but it was causing a forum user's file not to load.

bugfix(docdef): missing size value for es keymap

---

src/ansible_grid.c

It's useful for the `KR.DIR` op to simultaneously affect all tracks when you pass track 0, but this wasn't implemented. Also found that I wasn't bounds checking properly, so weird Teletype arguments to this op could probably corrupt Kria state.

KR.DIR: fix bounds checking, 0 for all tracks

---

src/ansible_grid.c

Some discussion here:
https://llllllll.co/t/ansible-development-and-beta-firmware-discussion/23118/166
Handy to be able to use this parameter from scripts instead of trying to measure Ansible's gate pulse length.

kria: support reading step duration via ii

---

src/ansible_grid.c

Kria measures the clock frequency to calculate gate durations and ratchet timing relative to the clock. When an incoming external clock stops completely, then starts again, the measurement code needs two rising edges to measure the clock rate, causing a different note duration for the first note played. 
This patch, when resetting the Kria playhead, replaces the previous measured edge time t_{-1} with t_{0} - \delta, where t_{0} is the current time and \delta is the existing edge measurement t_{-1} - t_{-2} , causing the next clock measurement to evaluate to t_{0} - (t_{0} - \delta) = \delta.
This resolves the issue described [here](https://llllllll.co/t/ansible-development-and-beta-firmware-discussion/23118/219), using Pamela's New Workout to clock / reset Kria in sync with other …

for discussion: use existing clock delta when applying kria reset

---

src/ansible_grid.c
src/main.c
src/main.h

Tweaks tuning mode so that you have three "save" buttons: save with a constant offset, save with linear interpolation between octaves, or save all tuning slots as-is. This is probably the way more common use case than all the other arbitrary tuning functionality. See https://llllllll.co/t/ansible-voltage-channel-discrepancy/29887

add UI to tune each channel by a constant offset

---

src/ansible_preset_docdef.c

Goofed this and it makes it impossible to save a JSON backup to disk in 3.0.0. Should maybe do a patch release for this, I'll post a build on the forum later today.

fix typo breaking USB backup

---

src/ansible_preset_docdef.c
tools/flash_tools/commands/extract/extract_presets.py
tools/flash_tools/commands/extract/extractor.py
tools/flash_tools/schemata/ansible/__init__.py
tools/flash_tools/schemata/ansible/ansible_preset_schema.py
tools/flash_tools/schemata/ansible/v300.py

I haven't done super extensive testing, but these changes appear to produce identical output to the on-device export for 3.0.0.
This PR also fixes the type of kria's `note_div_sync` in the on-device serialization. It was harmlessly(?) being recorded as a number instead of bool, which parses fine (I think?) but wasn't consistent with the canonical type and the extractor output.
I'm not sure if changing the default version strings to 3.0.0 everywhere is the right choice if the primary use case for this tool is still upgrading older preset files to the latest version.

Update flash_tools extractor script for ansible 3.0.0 schema

---

src/ansible_grid.c

When meta sequencing is on, hold the pattern key and tap a pattern slot to lock that pattern for editing -- the whole meta sequence continues to run, but the locked pattern's parameters are shown on all parameter pages so you can edit the locked pattern while listening to the whole metasequence. The pattern key flashes as long as the lock is engaged to remind you that the pattern you are editing is not necessarily the same as the one you're hearing. Suggested [here](https://llllllll.co/t/ansible-kria-feature-requests/4846/234).

kria: can lock which pattern is being edited in meta mode

---

src/ansible_ii_leader.c

Fix #84 - this helps restore Just Friends to normal operation when leader mode is deactivated.

reset JF velocity to max when exiting leader mode

---

src/ansible_grid.c
src/ansible_ii_leader.c
src/ansible_midi.c
src/main.c
src/main.h

Fixes #81 
* Midi mode will now use the user-customized tuning table and use the ii leader functions for sending pitch info.
* Fixed a bug where tuning mode was not properly exited if you pressed KEY1 on the panel.
* Closing the loop on the tuning issues described in https://github.com/monome/libavr32/pull/54 -- in addition to bringing the tuning table in line with Teletype's, the midi note offset is now applied as a semitone offset rather than an offset in DAC ticks, since a constant-valued offset is not the correct adjustment if the user has applied tuning customizations. To avoid breaking existing presets or Teletype behavior, the offsets are still _stored_ in terms of DAC ticks, but they are quantized to the nearest semitone value from the `ET` table to determine the right adjustment …

midi: fix tuning behavior & ii leader functionality

---

src/ansible_arc.c
src/ansible_grid.c
src/ansible_ii_leader.c
src/ansible_midi.c
src/ansible_tt.c
src/ansible_usb_disk.c
src/main.c
src/main.h

Fixes #86 as best as I can tell, see discussion there.
* Disables I2C while saving presets by changing the listening address to 0x03 -- this is a "reserved for future use" address for the I2C protocol so nothing should be using it.
* Change I2C terminology to match https://github.com/monome/libavr32/pull/55

use dummy i2c follower address during large flash writes to avoid lockup and preset loss

---

src/ansible_grid.c
src/ansible_ii_leader.c
src/ansible_ii_leader.h

added disting ex as a supported follower device.
since it has 4 modes, i had to shift the top right section for mode selection left by 1 button.

support for expert sleepers disting ex

---

src/ansible_grid.c
src/ansible_grid.h
src/ansible_preset_docdef.c

In Kria, a trigger to the reset input currently resets the playhead within the current pattern, but does not reset the metapattern playhead to the first pattern in the metapattern sequence. This patch adds a toggle to enable resetting the metapattern playhead as well, activated by holding key 2 (CONFIG) and pressing the bottom-right (pattern page select) key.
Common user request, e.g. https://llllllll.co/t/ansible-help-and-issues/21188/72, that I apparently put in the beta a while ago but forgot about.

kria: option for reset input to reset the metapattern playhead

---

src/ansible_preset_docdef.c

For reasons I haven't been able to tease apart yet, loading a preset file from disk is failing unless I remove this field. This isn't used for anything, it's just a marker at the start of the file that says it is an Ansible preset, which the filename already tells you.

drop unneeded firmware name in docdef

---

src/ansible_grid.c
src/ansible_ii_leader.c
src/ansible_ii_leader.h
src/main.c
src/main.h

- add W/syn as an additional ii follower. requires W/ [beta firmware w2b07](https://llllllll.co/t/mannequins-w-2-beta-testing/34091).
- add crow as an additional ii follower, sending pitch and velocity values to crow when ansible apps fire a trigger. requires crow firmware v2.1.2.
- split ii follower control functions out to a separate `ops` struct, saving on the amount of flash consumed for ii follower configuration
- fix a design problem where applying custom tuning adjustments to ansible's CV outputs would also affect pitches sent to ii followers, causing ii followers to play out of tune (huge thanks @scanner-darkly for testing / fixing this change for Disting EX)
- fix a [bug](https://github.com/monome/libavr32/pull/63) with JSON scalars that are split across two reads from the USB …

support W/syn and crow as ii followers

---

src/ansible_grid.c

Respond to the `ES.CV` ii command with the current pitch for a given channel.
Additionally, modified the other `CV` command responses for grid apps to send the "ideal" pitch from the `ET` table, rather than the stored pitch that might have been programmed by the user to calibrate for offsets between DACs -- this way ii getters should always read an in-tune pitch value, as is already the case with ii pitch values sent by ansible.

respond to ES.CV ii command

---

CHANGELOG.md

I added this as the last thing before the previous release and immediately forgot I had done so for the past year's worth of work.
I believe this Ansible revision is now ready for release (minus docs, gulp) but a beta of the current version was only posted today.

summarize changes since last release in CHANGELOG.md

---

src/ansible_grid.c

This has actually been a bug for quite a while, where drawing the time mod or probability mod pages when the selected parameter is "scale" or "pattern" causes an out of bound array access by `[k_mode]`, because `k_mode` > `KRIA_NUM_PARAMS` in these cases. In previous releases this was (perhaps) benign but in v3.1.1 this causes a [crash](https://llllllll.co/t/ansible-development-and-beta-firmware-discussion/23118/414) when tapping the "prob mod" key from the pattern page.
Probability mod doesn't do anything on the scale or pattern pages, so I just disabled it and don't light the key. Loop and time mods do have a meaning in metapattern mode, but the time division for metapattern mode was not displaying correctly, this is also fixed here.

kria: fix out-of-bounds access on pattern + prob page

---

src/ansible_arc.c
src/ansible_grid.c
src/main.c
src/main.h

- levels was not sending ii commands. We don't want to send a pitch update on every arc delta, so `set_cv_note_noii` just updates the DAC and updates the stored pitch, which will be sent to ii followers on the next rising edge of the gate.
- kria could crash due to an out-of-bounds access in metapattern mode. As far as I can tell removing this -1 adjustment still looks right as far as indicating the position of the metapattern playhead?

fix metapattern out of bounds and levels ii

---

src/ansible_grid.c
src/ansible_grid.h
tools/flash_tools/schemata/ansible/vnext.py

This is a long overdue PR of 256 grid support for kria that I've been using in sporadic live performances over the past couple years. In 2020 I reapplied the changes to the 3.0 firmware and I think I've worked out the obvious bugs. Last year I also took a swing at 256 support for Earthsea.
Kria changes:
* Using a 256 grid will show two independent kria views on the top and bottom halves of the grid. You can independently set mode, alt mode, modifier, etc. for the two views, or work on different tracks in the same mode.
Earthsea changes:
* Using a 256 grid will extend the playing surface over the entire grid. The extra space in column 0 is used for pattern-switching.
* With a 256 grid, the rune, edge, and voice views will appear on the lower half of the grid. In pattern view, the runes …

256 grid support for kria and earthsea

---

src/main.c

this is a fix to allow some follower devices to work properly with ansible running as i2c leader - this is the same delay teletype uses.
relevant discussion on lines: https://llllllll.co/t/i2c2midi-a-diy-module-that-translates-i2c-to-midi/40950/78

add a bootup delay when in leader mode

---

src/ansible_grid.c

Got a report on the teletype study group discord that certain presses on the bottom half of a zero hang ansible when in meadowphysics mode. Previous PR #99 didn't touch MP, but this basic protection should probably have been part of that.
(Bringing over some version of scanner's [standalone meadowphysics 256 branch](https://github.com/monome/meadowphysics/compare/main...scanner-darkly:meadowphysics:grid256) would be a good follow up, looking at how much work that would be.)

MP grid key handler should ignore bottom half of 256/zero

---

src/ansible_ii_leader.c
src/main.c

I was experiencing an ii freeze of txo and wsyn when powering on Ansible or loading a preset, if both txo and wsyn were enabled as followers. However, when having just one of them enabled during the load, and then only after the load enabling the other follower via the config page, things would work fine. Looking into it, this appears to be a bug in `reset_outputs()` in `src/main.c`, which loops through the 4 tracks and for each ii follower that is enabled for that track, calls its `mute` function. It looks like `n`, which represents the track number, was accidentally used instead of `i`, the index of the the ii follower, when getting the ii follower from `followers` and passing it to `mute`. Making this change resolved this freezing issue for me.
`reset_outputs` is called by the …

Fix ii mute bug on preset load
